batch_size: 12  # 设置批量大小
use_gpu: True  # 是否使用use_gpu
img_size: 512  # 输入图片大小
overlap: 64
epoches: 400
base_lr: 0.01  # 学习率
weight_decay: 2e-5
momentum: 0.9
power: 0.99
gpu_id: '1'
loss_type: 'ce'
save_iter: 10
num_workers: 1
val_visual: True
image_driver: 'gdal'   #pillow, gdal
color_txt: '../vai_data/color_table_isprs.txt'
num_class: 6  # some parameters
model_name: 'FANet101'  # ' unet, res_unet_psp, res_unet'
input_bands: 3
vis_graph: True

#data path
root_data: '../vai_data/cut_data'
dataset: 'massroad'
exp_name: '1108'
model_experision: 'v1'

val_path: '../vai_data/train_img/val'
val_gt: '../vai_data/val_gt'
test_path: '../vai_data/train_img/val'
save_path: '../result'

#mean4: 0.472455, 0.320782, 0.318403, 0.357
#std4: 0.144, 0.151, 0.211, 0.195
#mean: 0.472455, 0.320782, 0.318403
#std: 0.215084, 0.408135, 0.409993  # 标准化参数
#save_dir = '../{}_files'.format(exp_name)
#save_dir_model = os.path.join(save_dir, model_name+'_'+model_experision)
#if os.path.exists(save_dir) is False:
#    os.mkdir(save_dir)
#if os.path.exists(save_dir_model) is False:
#    os.mkdir(save_dir_model)
#data_dir = os.path.join(save_dir, 'data_slice_{}'.format(dataset))
#train_path = os.path.join(root_data, 'train')
#train_gt = os.path.join(root_data, 'train_labels')
#test_gt = os.path.join(root_data, 'test_labels')
#output = os.path.join(save_dir_model, './result_{}/'.format(model_name))
#output_gray = os.path.join(save_dir_model, './result_gray_{}/'.format(model_name))
#model_dir = os.path.join(save_dir_model, './pth_{}/'.format(model_name))